name: Python Nox CI

# This is a temporary workflow to run format and unit tests using Nox.
# It is intended to be manually triggered and will not run on pull requests or pushes.
# Once this is fully tested and stable, we might replace the existing Python CI workflow with this one
# to speed it up and simplify the process.

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  format-and-unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Nox
        run: |
          NOXFILE="./path/to/noxfile/noxfile.py"
          if [ -f "$NOXFILE" ]; then
            echo "NOXFILE_PATH=$NOXFILE" >> $GITHUB_ENV
            echo "noxfile found, environment variable set."
          else
            echo "Error: noxfile.py not found at $NOXFILE"
            exit 1
          fi
          # Install uv to speed up virtual environments installation
          curl -LsSf https://astral.sh/uv/install.sh | sh
          pip install nox

      - name: Run Code Quality Checks
        if: ${{ matrix.python-version == '3.10' }}
        run: |
          nox -f ${{ env.NOXFILE_PATH }} -s lint

      - name: Run Unit Tests
        run: |
          PYTHON_VERSIONS="${{ matrix.python-version }}" nox -f ${{ env.NOXFILE_PATH }} -s unit

      - name: Run Unit Tests (specific plugins)
        run: |
          PYTHON_VERSIONS="${{ matrix.python-version }}" nox -f ${{ env.NOXFILE_PATH }} -s unit-plugins